apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-app
  namespace: workshop
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: echo-app
  targetCPUUtilizationPercentage: 20
