apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: apetani/php-app:latest
        name: php
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
      - image: apetani/nginx-app:latest
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
        - name: nginx-default-conf
          configMap:
            name: nginx-default-conf
            defaultMode: 0664