apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-app
  namespace: workshop
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: echo-app
  targetCPUUtilizationPercentage: 1
