version: "3.5"

services:
  react:
    image: node:8.16.0
    container_name: ${PROJ}_${ENV}_react_svc
    ports:
      - "${REACT_PORT}:3000"
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
    working_dir: /app
    entrypoint: sh -c "npm i && npm start"
    networks:
      - workshop

volumes:
  node_modules:
    name: ${PROJ}_${ENV}_node_modules

networks:
  workshop:
    name: ${PROJ}_${ENV}_workshop_local